### ISSUE TITLE
Issue with updub

### ISSUE THREAD

**Issue by nine1six** [anjanms/DubAPI#17]
For some reason the bot is throwing this error when the updub method is passed. Any idea why?

events.js:141
      throw er; // Unhandled 'error' event
      ^
DubAPIRequestError: Response 404 from room/55fc4c06c59e310300fd650d/playlist/5696fb3d066e0d2c00f6cb7b/dubs
    at Error.DubAPIRequestError (/home/ubuntu/node_modules/dubapi/lib/errors/requestError.js:4:11)
    at Request.<anonymous> (/home/ubuntu/node_modules/dubapi/lib/requestHandler.js:114:70)
    at emitTwo (events.js:92:20)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/home/ubuntu/node_modules/dubapi/node_modules/request/request.js:1035:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/home/ubuntu/node_modules/dubapi/node_modules/request/request.js:962:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)

**Comment by anjanms** [comment]
This is due to an issue with the Dubtrack API, the same thing happens in the background on the web frontend. Despite the error, the request is still processed.

To my knowledge this has been reported to the dubtrack devs but hasn't been fixed.
In the meantime you can suppress the error by passing a noop function to updub/downdub.
